import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home({ coins }) {
  console.log(coins);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          {coins.map((data) => {
            return (
              <Link
                href="/coins"
                as={`/coins/${data.id}`}
                className={styles.card}
                key={data.id}
              >
                <img src={data.image} width="30" />
                <h2>{data.name}</h2>
                <p>{data.symbol}</p>
              </Link>
            );
          })}
        </div>
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const response = await fetch(
    "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=10&page=1&sparkline=false"
  );
  const coins = await response.json();
  return {
    props: {
      coins,
    },
  };
}
